# *** Generated by ConfigerIO ***
# {{{timestamp}}}

[{{name}}]

chdir = /home/{{name}}/www

listen.mode = 0666
listen = /run/php-{{name}}.sock
listen.owner = {{name}}
listen.group = {{name}}

pm = ondemand
pm.max_children = 10
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.process_idle_timeout = 60s
pm.max_requests = 20
