# *** Generated by ConfigerIO ***
# {{{timestamp}}}
# {{{domain}}}
#
# <don't edit here; changes will be overwritten>

server {
	listen *:80;
	server_name {{{domain}}};

	root /home/{{{user}}}/www/;
	index index.php index.html index.htm;

	access_log /var/log/nginx/access_{{{domain}}}.log;
	error_log  /var/log/nginx/error_{{{domain}}}.log warn;

	location / {
		try_files $uri $uri/ $uri/index.php /index.php =404;
		autoindex on;
		autoindex_exact_size off;
	}

#	error_page 404 /404.html;
#		location = /40x.html {
#	}
#	error_page 500 502 503 504 /50x.html;
#		location = /50x.html {
#	}

{{#if has-php}}
	location ~* \.php$ {
		fastcgi_pass unix:/run/php-{{{user}}}.sock;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
		include /etc/nginx/fastcgi_params;
	}
{{/if}}

}
