# *** Generated by ConfigerIO ***
# {{{timestamp}}}
#
# <don't edit here; changes will be overwritten>
# /etc/sysconfig/iptables

*filter
:INPUT   ACCEPT [0:0]
:OUTPUT  ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
-P INPUT   ACCEPT
-P OUTPUT  ACCEPT
-P FORWARD ACCEPT

# localhost
-A INPUT  -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT

# established
-A INPUT   -m state --state ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT  -m state --state ESTABLISHED,RELATED -j ACCEPT
-A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

# ping
-A INPUT -p icmp -j ACCEPT

# dns
#-A OUTPUT -p udp -o pub --dport 53 -j ACCEPT
#-A INPUT  -p udp -i pub --sport 53 -j ACCEPT
#-A OUTPUT -p udp -o lan --dport 53 -j ACCEPT
#-A INPUT  -p udp -i lan --sport 53 -j ACCEPT



# default reject
-A INPUT   -j REJECT
-A OUTPUT  -j ACCEPT
-A FORWARD -j ACCEPT
COMMIT
