// *** Generated by ConfigerIO ***
// {{{timestamp}}}


options {
	listen-on    port 53 { any; };
	listen-on-v6 port 53 { any; };

	recursion no;
	dnssec-validation auto;
	allow-transfer { "none"; };

	directory          "/var/named";
	pid-file           "/run/named/named.pid";
	session-keyfile    "/run/named/session.key";
	dump-file          "/var/named/data/cache_dump.db";
	managed-keys-directory "/var/named/dynamic";
	geoip-directory    "/usr/share/GeoIP";
	statistics-file    "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	secroots-file      "/var/named/data/named.secroots";
	recursing-file     "/var/named/data/named.recursing";

	include "/etc/crypto-policies/back-ends/bind.config";
};


logging {
	channel default_log {
		file "/var/log/named/named.log" versions 5 size 128M;
		print-time yes;
		print-severity yes;
		print-category yes;
		severity warning;
	};
	category default { default_log; };
	category general { default_log; };
};


view external {
	allow-query { any; };
	recursion no;
	additional-from-cache no;
	{{#each external}}

	zone "{{{this}}}" IN {
		type master;
		file "/etc/named/{{{this}}}.zone";
	};
	{{/each}}

	allow-update { none; };
};
